#ifndef __H_KEYS_H
#define __H_KEYS_H

enum{
   K_NOKEY=-1,
   K_CTRLBREAK=3, K_BACKSPACE=8, K_TAB,
   K_ENTER=13, K_GREYENTER=13, K_LSHIFT=16, K_RSHIFT=16,
   K_LCTRL, K_RCTRL=17, K_LALT, K_RALT=18, K_PAUSE, K_CAPSLOCK,
   K_ESC=27,
   K_SPACE=32,
   K_0=48, K_1, K_2, K_3, K_4, K_5, K_6, K_7, K_8, K_9,
   K_A=65, K_B, K_C, K_D, K_E, K_F, K_G, K_H,
   K_I, K_J, K_K, K_L, K_M, K_N, K_O, K_P,
   K_Q, K_R, K_S, K_T, K_U, K_V, K_W, K_X,
   K_Y, K_Z,

   K_PAGEUP=128, K_PAGEDOWN, K_END, K_HOME,
   K_CURSORLEFT, K_CURSORUP, K_CURSORRIGHT, K_CURSORDOWN,
   K_PRTSCR, K_INS, K_DEL,
   K_GREYMULT, K_GREYPLUS, K_CENTER, K_GREYMINUS,
   K_GREYSLASH, K_F1, K_F2, K_F3, K_F4, K_F5, K_F6,
   K_F7, K_F8, K_F9, K_F10, K_F11, K_F12,
   K_NUMLOCK, K_SCROLLLOCK
};

#endif