//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by main.rc
//
#define IDC_PROP_TAB                    1
#define IDC_BUTTON_LIGHT_SPECULAR       1
#define IDC_CT_DISABLED                 4
#define IDC_CT_NORMAL                   10
#define IDC_MESH_INFO                   132
#define IDC_RESET_POS                   1000
#define IDC_LIST1                       1001
#define IDC_RESET_ROT                   1001
#define IDC_RESET_SCL                   1002
#define IDC_RESET_LINK                  1003
#define IDC_RESET_NU_SCL                1004
#define IDC_RADIO_COLCCYL               1006
#define IDC_LIST                        1007
#define IDC_RESET_FRM_FLAGS             1008
#define IDC_RESET_BRIGHTNESS            1009
#define IDC_CHECK_VIS                   1009
#define IDC_CHECK_LIGHT                 1010
#define IDC_CHECK_SND                   1011
#define IDC_CHECK_MODEL                 1013
#define IDC_RADIO_COLBOX                1014
#define IDC_CHECK_HIER                  1015
#define IDC_CHECK_SCT                   1017
#define IDC_CHECK_DUM                   1018
#define IDC_RADIO_COLRECT               1019
#define IDC_CHECK_HIDE                  1020
#define IDC_CHECK_CAM                   1021
#define IDC_RADIO_COLCYL                1022
#define IDC_CHECK_OCC                   1023
#define IDC_RADIO_COLSHP                1024
#define IDC_CHECK_JOINT                 1025
#define IDC_CHECK_USER                  1026
#define IDC_BUTTON_GRP_ALL              1027
#define IDC_BUTTON_GRP_NONE             1028
#define IDC_BUTTON_SEL_ALL              1029
#define IDC_BUTTON_SEL_NONE             1030
#define IDC_BUTTON_SEL_INV              1031
#define IDC_CHECK_VOL                   1032
#define IDC_INC_SEL                     1063
#define IDC_MRG_SETTINGS                1065
#define IDC_NUM_SEL                     1065
#define IDC_MRG_LIGHT_L                 1068
#define IDC_MRG_LIGHT_E                 1069
#define IDC_MRG_SOUND_L                 1070
#define IDC_MRG_SOUND_E                 1071
#define IDC_MRG_MODEL_L                 1072
#define IDC_MRG_MODEL_E                 1073
#define IDC_MRG_VOLUME_L                1074
#define IDC_MRG_VOLUME_E                1075
#define IDC_EDIT_LIGHT_POWER            1075
#define IDC_MRG_DUMMY_L                 1076
#define IDC_EDIT_LIGHT_SPECULAR_POWER   1076
#define IDC_MRG_DUMMY_E                 1077
#define IDC_EDIT_LIGHT_SPECULAR_SPECULAR_ANGLE 1077
#define IDC_MRG_CAMERA_L                1078
#define IDC_EDIT_FRM_NAME               1078
#define IDC_MRG_CAMERA_E                1079
#define IDC_EDIT_FRM_POS_Y              1079
#define IDC_EDIT_FRM_POS_Z              1080
#define IDC_MRG_SCRIPT_L                1082
#define IDC_MRG_SCRIPT_E                1083
#define IDC_MRG_LMAP                    1085
#define IDC_MRG_OCCLUDER_L              1086
#define IDC_MRG_OCCLUDER_E              1087
#define IDC_BUTTON_MODEL_BROWSE         1089
#define IDC_BUTTON_MODEL_SAME_AS        1090
#define IDC_EDIT_FRM_POS_X              1091
#define IDC_BUTTON_MODEL_RELOAD         1092
#define IDC_EDIT_FRM_SCALE_U            1093
#define IDC_EDIT_FRM_ROT_X              1094
#define IDC_EDIT_FRM_ROT_Y              1095
#define IDC_EDIT_FRM_ROT_Z              1096
#define IDC_STATIC_CURR_DIR             1097
#define IDC_EDIT_FRM_ROT_A              1097
#define IDC_STATIC_NEW_DIR              1098
#define IDC_COMBO_LIGHT_TYPE            1098
#define IDC_EDIT_FRM_PARENT             1098
#define IDC_BUTTON_OPEN_LAST            1099
#define IDC_EDIT_LIGHT_RANGE_N          1099
#define IDC_LAST_MISSION                1100
#define IDC_EDIT_LIGHT_RANGE_F          1100
#define IDC_EDIT_LIGHT_CONE_IN          1101
#define IDC_EDIT                        1102
#define IDC_EDIT_LIGHT_CONE_OUT         1102
#define IDC_CHECK_LIGHT_MODE_V          1103
#define IDC_WRITABLE                    1104
#define IDC_THUMBNAIL                   1104
#define IDC_CHECK_LIGHT_MODE_LM         1104
#define IDC_CHECKIN_KEEP                1105
#define IDC_COMBO_SOUND_TYPE            1105
#define IDC_CHECK_LIGHT_MODE_SHD        1105
#define IDC_TABEDIT_CLOSE               1106
#define IDC_EDIT_SOUND_FILE             1106
#define IDC_CHECK_LIGHT_MODE_DYN        1106
#define IDC_FAV0                        1107
#define IDC_TABEDIT_CK_OUT              1107
#define IDC_EDIT_SOUND_RANGE_N          1107
#define IDC_TABEDIT_CK_IN               1108
#define IDC_EDIT_SOUND_RANGE_F          1108
#define IDC_FAV1                        1109
#define IDC_EDIT_SOUND_SIZE             1109
#define IDC_FAV2                        1110
#define IDC_EDIT_SOUND_CONE_IN          1110
#define IDC_FAV3                        1111
#define IDC_EDIT_SOUND_CONE_OUT         1111
#define IDC_FAV_SET                     1112
#define IDC_EDIT_SOUND_VOL              1112
#define IDC_FAV4                        1113
#define IDC_EDIT_SOUND_VOL_OUT          1113
#define IDC_FAV5                        1114
#define IDC_CHECK_SOUND_MODE_ON         1114
#define IDC_FAV6                        1115
#define IDC_CHECK_SOUND_MODE_LOOP       1115
#define IDC_FAV7                        1116
#define IDC_CHECK_SOUND_MODE_STREAM     1116
#define IDC_FAV_INFO                    1117
#define IDC_EDIT_MODEL_NAME             1117
#define IDC_BUTTON_LIGHT_COLOR          1118
#define IDC_BUTTON_SOUND_BROWSE         1119
#define IDC_LIST_LSECTORS               1121
#define IDC_BUTTON_LSECTORS_PICK        1122
#define IDC_BUTTON_LSECTORS_ALL1        1123
#define IDC_COMBO_VOLUME_TYPE           1124
#define IDC_BUTTON_LSECTORS_SELECT      1124
#define IDC_BUTTON_LSECTORS_NO1         1125
#define IDC_COMBO_COL_MAT               1126
#define IDC_BUTTON_LIGHT_SAME_AS        1127
#define IDC_COMBO_VISUAL_TYPE           1141
#define IDC_EDIT1                       1144
#define IDC_BUTTON_LOG_SAVE             1144
#define IDC_SEARCH_WHOLE                1145
#define IDC_BUTTON_LOG_CLOSE            1145
#define IDC_SEARCH_CASE                 1146
#define IDC_PREVIEW                     1148
#define IDC_CHECK_PRV_ANIMATE           1149
#define IDC_CHECK_PRV_SHOW              1150
#define IDC_CHECK_SND_PRV_SHOW          1151
#define IDC_SOUND_DETAILS               1152
#define IDC_CHECK_SND_PRV_LOOP          1153
#define IDC_EDIT_VOL_NUSCALE_X          1154
#define IDC_EDIT_VOL_NUSCALE_Y          1155
#define IDC_EDIT_VOL_NUSCALE_Z          1156
#define IDC_MRG_CHECKPOINTS             1160
#define IDC_BUTTON_SCRIPT_OPEN          1168
#define IDC_BUTTON_SCRIPT_ASSIGN        1169
#define IDC_CHECK_VOL_SINGLE            1169
#define IDC_BUTTON_SCRIPT_DEL           1170
#define IDC_CHECK_VOL_STATIC            1170
#define IDC_BUTTON_SCRIPT_EDIT          1171
#define IDC_EDIT_LOG1                   1171
#define IDC_BUTTON_SCRIPT_CLOSE         1172
#define IDC_LIST_SSECTORS               1172
#define IDC_BUTTON_SCRIPT_CHECK_OUT     1173
#define IDC_BUTTON_SSECTORS_ALL1        1173
#define IDC_BUTTON_SCRIPT_COMP          1174
#define IDC_BUTTON_SSECTORS_NO1         1174
#define IDC_BUTTON_SCRIPT_REMOVE        1175
#define IDC_BUTTON_SSECTORS_PICK        1175
#define IDC_BUTTON_SCRIPT_SELECT        1176
#define IDC_BUTTON_SSECTORS_SELECT      1176
#define IDC_BUTTON_SCRIPT_CHECK_IN      1177
#define IDC_CHECK_NO_SHADOW             1177
#define IDC_BUTTON_SCRIPT_DUMP          1178
#define IDC_CHECK_NO_COLL               1178
#define IDC_BUTTON_SCRIPT_SEARCH        1179
#define IDC_RADIO_OCCMESH               1179
#define IDC_RADIO_OCCSHP                1180
#define IDC_ALIGN_X                     1181
#define IDC_ALIGN_Y                     1182
#define IDC_ALIGN_Z                     1183
#define IDC_PH_RESET                    1200
#define IDC_COLM_PIVOT                  1200
#define IDC_COLM_VERTEX                 1201
#define IDC_SEED_ROTATION               1206
#define IDC_SEED_SET_NAME               1210
#define IDC_SEED_DELETE_SET             1211
#define IDC_SEED_CREATE_SET             1212
#define IDC_SEED_DELETE_MODEL           1213
#define IDC_SEED_RENAME_SET             1214
#define IDC_SEED_ADD_MODELS             1215
#define IDC_SEED_PUT                    1216
#define IDC_SEED_MODELS                 1217
#define IDC_SEED_BROWSE_MODEL           1218
#define IDC_VIS_PROP_GROUP_BASE         1218
#define IDC_SPEEDSLIDER                 1219
#define IDC_SPEEDVALUE                  1220
#define IDC_LINK                        1221
#define IDC_FALL_Z                      1222
#define IDC_HIDE                        1223
#define IDC_BUTTON_VISUAL_SAME_AS       1224
#define IDC_CHECK_SHADOW_CAST           1225
#define IDC_CHECK_SHADOW_REC            1226
#define IDC_CHECK_VOLUME_STATIC         1228
#define IDC_BUTTON_VISUAL_SAME_AS2      1229
#define IDC_BUTTON_VISUAL_COPY          1230
#define IDC_DUMP                        1234
#define IDC_BUTTON_DUMP_CLOSE           1235
#define IDC_MODEL_MISSION               1237
#define IDC_ITEM_SELECT                 1239
#define IDC_COMBO_SCT_ENV               1240
#define IDC_SLIDER_LOD                  1241
#define IDC_EDIT_LOD                    1242
#define IDC_EDIT_LOD_RANGE              1243
#define IDC_SLIDER_LOD_SCALE            1244
#define IDC_HI                          1245
#define IDC_LOD_SCALE                   1245
#define IDC_MAXF                        1246
#define IDC_LOD_SET_DEFAULT             1246
#define IDC_FUDGE                       1247
#define IDC_KEY_TIME                    1247
#define IDC_BOUNCE                      1248
#define IDC_PH_BODY                     1249
#define IDC_PH_JOINT                    1250
#define IDC_NOTIFY                      1250
#define IDC_PH_JTYPE                    1251
#define IDC_ANIM_NAME                   1251
#define IDC_PH_BODY_STATIC              1252
#define IDC_CFM                         1253
#define IDC_FIRST_KEY                   1253
#define IDC_S_ERP                       1254
#define IDC_REMOVE_FRAME                1254
#define IDC_S_CFM                       1255
#define IDC_TIME_SLIDER                 1255
#define IDC_SU_ERP                      1256
#define IDC_PLAY_TOGGLE                 1256
#define IDC_SU_CFM                      1257
#define IDC_LO                          1258
#define IDC_LO1                         1259
#define IDC_LAST_KEY                    1259
#define IDC_HI1                         1260
#define IDC_PREV_KEY                    1260
#define IDC_LO2                         1261
#define IDC_NEXT_KEY                    1261
#define IDC_HI2                         1262
#define IDC_PH_DENSITY                  1263
#define IDC_MODEL_NAME                  1265
#define IDC_KEY_NUM                     1266
#define IDC_PH_UNIT_DENSITY             1267
#define IDC_PH_UNIT_WEIGHT              1268
#define IDC_ST_TIME                     1269
#define IDC_ANIM_FRM_LIST               1271
#define IDC_ADD_KEY                     1273
#define IDC_DEL_KEY                     1274
#define IDC_COPY_POSE                   1275
#define IDC_CLEAR                       1276
#define IDC_PASTE_POSE                  1276
#define IDC_ALL                         1277
#define IDC_COPY                        1278
#define IDC_FRM_LIST2                   1279
#define IDC_SEL                         1279
#define IDC_ADD                         1280
#define IDC_PROC_LIST                   1281
#define IDC_TILE                        1282
#define IDC_TIME                        1283
#define IDC_FILTER                      1284
#define IDC_REMOVE                      1285
#define IDC_MODE                        1286
#define IDC_DELETE                      1287
#define IDC_SMOOTH                      1288
#define IDC_NEW                         1289
#define IDC_SPEED                       1289
#define IDC_EASY_FROM                   1290
#define IDC_EASY_TO                     1291
#define IDC_PAUSE                       1292
#define IDC_PICK_NOTIFY_FRM             1292
#define IDC_NOTIFY_LINK                 1293
#define IDC_DUPLICATE                   1294
#define IDC_POS_CHECK                   1296
#define IDC_ROT_CHECK                   1297
#define IDC_POW_CHECK                   1298
#define IDC_TRANS_ALL                   1299
#define IDC_TRANS_CLEAR                 1300
#define IDC_MODE_SELECT                 1303
#define IDC_NEW_MODE                    1304
#define IDC_DELETE_MODE                 1305
#define IDC_MASK_NAME                   1306
#define IDC_PICK_MASK                   1307
#define IDC_RELOAD                      1308
#define IDC_PLAY_TIME                   1314
#define IDC_CHANGE_MODEL                1315
#define IDC_ERRORS                      1316
#define IDC_ERR_TITLE                   1317
#define IDC_ADD_FRAME                   1318
#define IDC_NOTE_CLEAR                  1321
#define IDC_NAME_EDIT                   1324
#define IDC_SELECT_MASK                 1325
#define IDC_NEW_MASK                    1326
#define IDC_STATIC_NAME                 1327
#define IDC_ANIM_TIME_SCALE             1328
#define IDC_WEIGHT                      1330
#define IDC_SLIDER1                     1331
#define IDC_EDIT_WEIGHT                 1332
#define IDC_SPIN_EASY_FROM              1333
#define IDC_SPIN_EASY_TO                1334
#define IDC_SPIN_SMOOTH                 1335
#define IDC_SPIN_SPEED                  1336
#define IDC_PASTE_MIRROR                1336
#define IDC_SPIN_NOTE0                  1337
#define IDC_INSERT_TIME                 1337
#define IDC_SPIN_NOTE1                  1338
#define IDC_SMOOTH_ANIM_SPEED           1338
#define IDC_SPIN_NOTE2                  1339
#define IDC_SPIN_NOTE3                  1340
#define IDC_ANIM_NAME1                  1342
#define IDC_NOTIFY_GROUP                1343
#define IDC_EASY_FROM_TITLE             1344
#define IDC_EASY_TO_TITLE               1345
#define IDC_SMOOTH_TEXT                 1346
#define IDC_SPEED_TITLE                 1347
#define IDC_MODEL_NAME_TITLE            1347
#define IDC_PAUSE_TITLE                 1348
#define IDC_NOTIFY_LINK_TITLE           1348
#define IDC_PASTE_POSE_SELECTION        1350
#define IDC_PASTE_POSE_SELECTION_KEYS   1351
#define IDC_EDIT_MODEL_BRIGHTNESS       1353
#define IDC_TRANSFORM_GRP               1354
#define IDC_KEY_DATA                    1356
#define IDC_NOTE0                       1357
#define IDC_RESCALE_SPEED               1358
#define IDC_SECT_SEL_LIGHTS             1359
#define IDC_NOTE1                       1359
#define IDC_ALIGN_MODE                  1360
#define IDC_SECT_SEL_SOUNDS             1360
#define IDC_NOTE2                       1360
#define IDC_SET_DATA                    1361
#define IDC_NOTE3                       1361
#define IDC_ALIGN_MODE_TITLE            1362
#define IDC_SCALE_TITLE                 1363
#define IDC_SCALE                       1364
#define IDC_EDIT_TEMPERATURE            1365
#define IDC_ANIMS_TREE                  1366
#define IDC_CAMPATH_LIST                1367
#define IDC_NOTE_POS0                   1371
#define IDC_NOTE_POS1                   1372
#define IDC_NOTE_POS2                   1373
#define IDC_NOTE_POS3                   1374
#define IDC_EASINESS_TEXT               1375
#define IDC_EASINESS1                   1378
#define IDC_SPIN_EASINESS               1379
#define IDC_SIZE_X                      1388
#define IDC_SIZE_Y                      1389
#define IDC_FPS                         1390
#define IDC_RESET_VOL_TYPE              1392
#define IDC_RESET_COL_MAT               1393
#define IDC_RESET_LIGHT                 1394
#define IDC_VISUAL_PROPS                1407
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         40079
#define _APS_NEXT_CONTROL_VALUE         1300
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
